### ISSUE TITLE
Digits activity still active at the end of auth process

### ISSUE THREAD

**Issue by pecheriere** [twitter/digits-android#5]
Hi,

I have build an app to test Digits (using Fabric to install it). I use Digits 1.6.1. I'm using the button and code provided in the documentation. My device is a Note 3 with Android 5.

All the auth process works, but at the end, when I still can see the digits activity in the "all current activity" view of my phone.

First my Activity
![1](https://cloud.githubusercontent.com/assets/1872741/8391647/c36ab46c-1cc1-11e5-8fd0-2d1bdb52d928.png)

Then I do the auth process
![2](https://cloud.githubusercontent.com/assets/1872741/8391648/c4849a3e-1cc1-11e5-88bf-a6fa19c941d2.png)

I received the code and get back to my Activity but still si an other Activity
![3](https://cloud.githubusercontent.com/assets/1872741/8391649/c5da4636-1cc1-11e5-8d32-8a5e46fa48d8.png)

The other activity is the Activity asking for the phone number.
![4](https://cloud.githubusercontent.com/assets/1872741/8391651/c7a8df2c-1cc1-11e5-88af-affbc2672816.png)

Note the activity remaining active is the one asking for the phone number, and not the last one asking for the code.

**Comment by pecheriere** [comment]
Using the 1.5.0 version I don't have this issue.

**Comment by efrohnhoefer** [comment]
@pecheriere thanks for the issue report we will look into the issue.

**Comment by anuragopenxcell** [comment]
Still facing this issue in 1.8.0

**Comment by tuomaslaa** [comment]
Same issue here with 1.8.0

**Comment by rameshvoltella** [comment]
the same issue for me too please fix this

**Comment by scruffyfox** [comment]
Also having this issue. Activity is launched as a "new task" and not dismissed on callback

**Comment by DenisBronx** [comment]
Same issue here with 1.9.0

**Comment by mdenissov** [comment]
Also having this issue.

**Comment by farukcankaya** [comment]
Having same issue 1.9.0

**Comment by se-bastiaan** [comment]
This is due to the task affinity of the digits activities (as mentioned before). It seems that [this](https://github.com/twitter/digits-android/blob/76a1c0bdf8a885fe17029dd2b1cdeda28d105459/digits/src/main/java/com/digits/sdk/android/DigitsControllerImpl.java#L164) should stop all activities in the task affinity. But it doesn't. Since `CommonUtils` is a Fabric class I cannot check what it does but I suspect it should call `ActivityCompat.finishActivity(Activity activity)` but that doesn't work somehow.

**Comment by PatrickDattilio** [comment]
We really need some way to turn this off. I have significant numbers of users who are struggling to use Digits. Is there some reason you need to open the Digits activity in a new task? This is a significant usability issue with a seemingly trivial fix. Remove, or give us the option to turn off, FLAG_ACTIVITY_NEW_TASK

**Comment by thomazfeitoza** [comment]
+1 for PatrickDattilio's suggestion

**Comment by PatrickDattilio** [comment]
This has been resolved in the latest version of Digits!

**Comment by efrohnhoefer** [comment]
This issue will be addressed in the release 1.9.2 release. We were using the ACTIVITY_NEW_TASK because the Activity was being launched using a Application Context provided by Fabric. On API 14+ we will use the ActivityLifecycleCallbacks to determine the current Activity and use the associated context to launch Digits without the ACTIVITY_NEW_TASK flag.

See: https://github.com/twitter/digits-android/commit/3335d2da66d0db06d00daae7d95433c36c4f1822

**Comment by srinivasanj** [comment]
I am using release 1.10.3 and this issue still exists...

How do I get past this?

**Comment by lookitsatravis** [comment]
@efrohnhoefer - I know this has been closed since December, but I'm having this exact issue in the 2.0.0 release.

**Comment by fxhereng** [comment]
Same issue with 1.11.2, having a black activity kept, when clicking on it it throws an exception:

`/com.digits.sdk.android.PhoneNumberActivity}: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()`
